// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa2QHcXD4OInKNM3lya-V8oetrJWZqKZI',
    appId: '1:171153443672:web:a787afbf7b4726287fb32d',
    messagingSenderId: '171153443672',
    projectId: 'my-simple-app-todo',
    authDomain: 'my-simple-app-todo.firebaseapp.com',
    storageBucket: 'my-simple-app-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRvLpTKzWm6Me6Ic3zp1UwtRO-xJD96v0',
    appId: '1:171153443672:android:cc0eab0c79aab1647fb32d',
    messagingSenderId: '171153443672',
    projectId: 'my-simple-app-todo',
    storageBucket: 'my-simple-app-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENqgrSIIBW8FpYDedW0jkW-TbOAUQ0Us',
    appId: '1:171153443672:ios:6794c4f87425887c7fb32d',
    messagingSenderId: '171153443672',
    projectId: 'my-simple-app-todo',
    storageBucket: 'my-simple-app-todo.appspot.com',
    iosBundleId: 'com.example.todoSimpleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDENqgrSIIBW8FpYDedW0jkW-TbOAUQ0Us',
    appId: '1:171153443672:ios:6794c4f87425887c7fb32d',
    messagingSenderId: '171153443672',
    projectId: 'my-simple-app-todo',
    storageBucket: 'my-simple-app-todo.appspot.com',
    iosBundleId: 'com.example.todoSimpleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa2QHcXD4OInKNM3lya-V8oetrJWZqKZI',
    appId: '1:171153443672:web:6e6e2d468b518b547fb32d',
    messagingSenderId: '171153443672',
    projectId: 'my-simple-app-todo',
    authDomain: 'my-simple-app-todo.firebaseapp.com',
    storageBucket: 'my-simple-app-todo.appspot.com',
  );

}